import Head from 'next/head';
import { Inter } from 'next/font/google';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';
import data from '../../data/servicio.json';
import Search from '@/components/Search';

const inter = Inter({ subsets: ['latin'] });
console.log(inter);

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar data={data} />
      <div className="container">
        <Search />
      </div>
      <Footer />
    </>
  );
}
